// client_a/src/app/shared/components/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { Router } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';
import { SocketService } from '../../../core/services/socket.service';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [RouterLink],
  template: `
    <nav class="navbar">
      <div class="navbar-links">
        <a routerLink="/dashboard" class="btn">Users</a>
        <a routerLink="/conversations" class="btn">Chats</a>
      </div>
      <button class="btn" (click)="logout()">Logout</button>
    </nav>
  `,
  styles: [`
    .navbar {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 0.75rem 1.5rem;
      border-bottom: 1px solid var(--border-strong);
      background: var(--bg);
    }
    .navbar-links {
      display: flex;
      gap: 0.5rem;
    }
  `]
})
export class NavbarComponent {
  constructor(
    private auth: AuthService,
    private socket: SocketService,
    private router: Router
  ) {}

  logout(): void {
    this.socket.disconnect();
    this.auth.logout();
    this.router.navigate(['/login']);
  }
}

// client/src/components/Navbar.tsx
import React from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../hooks/useAuth";

export function Navbar(): React.JSX.Element {
  const { clearUser } = useAuth();
  const navigate = useNavigate();

  const handleLogout = (): void => {
    clearUser();
    navigate("/login");
  };

  const linkStyle: React.CSSProperties = {
    padding: "0.4rem 1rem",
    borderRadius: "6px",
    border: "1px solid #e5e7eb",
    background: "transparent",
    color: "#111827",
    cursor: "pointer",
    fontSize: "0.9rem",
    textDecoration: "none",
  };

  return (
    <nav
      aria-label="Main navigation"
      style={{
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        padding: "0.75rem 1.5rem",
        borderBottom: "1px solid #e5e7eb",
        backgroundColor: "#fff",
      }}
    >
      {/* Left — nav links */}
      <div style={{ display: "flex", gap: "0.5rem" }}>
        <Link to="/dashboard" style={linkStyle}>Users</Link>
        <Link to="/conversations" style={linkStyle}>💬 Chats</Link>
      </div>

      {/* Right — logout */}
      <button
        type="button"
        onClick={handleLogout}
        style={{
          padding: "0.4rem 1rem",
          borderRadius: "6px",
          border: "1px solid #e5e7eb",
          background: "transparent",
          color: "#111827",
          cursor: "pointer",
          fontSize: "0.9rem",
        }}
      >
        Logout
      </button>
    </nav>
  );
}
